### ISSUE TITLE
Proposal: DWriteCore example in C# & xaml

### ISSUE THREAD

**Issue by WelterDevelopment** [microsoft/WindowsAppSDK-Samples#51]
As a hobby C#/.NET developer coming from UWP, I understand exactly nothing regarding the "Text Rendering" capability of Project Reunion. I thought C# & xaml is pretty much the standard way to develop new apps for Windows? Both the online documentation and this TextRendering example are quite incomprehensible for me.
Please add an example written in C# & xaml, so that it is more readable and understandable!

**Comment by duncanmacmichael** [comment]
Hi @WelterDevelopment , thanks so much for your interest in the App SDK and DWriteCore specifically. I'll try to explain without getting into too much detail. :) 

The TL;DR is that DWriteCore is a nano-COM C++ API and does not have a C# version available, so there are no such samples as you're asking for. It is a low-level API for rendering text on the system, and is seldom called by individual developers unless your app does some serious font manipulation. Most consumers of DWrite are either big apps like Office and Edge, or higher-level frameworks that take care of all font-related things for you in their various controls. If you're using C#/XAML, you'll probably use XAML controls for text and thus don't need to worry about calling into DWriteCore.

Outside the App SDK, C# apps can access DWrite through Win2D, which wraps D2D and DWrite. At the moment, however, we're in the process of working on a version of Win2D for the App SDK and it isn't available yet. We did go ahead and put DWriteCore into the App SDK mostly to get ahead of the game, and because eventually we'd like all developers to target the App SDK by default. We're just still working our way there.

Hope this helps!

**Comment by WelterDevelopment** [comment]
Thank you for the clarification! Sadly, the XAML text editing controls of WinUI are not suitable for syntax highlighted code >1000 lines. In my understanding, the RichEditBox control does not run on Win2D/DWrite as it is extremely slow and unstable. So after  lots of research I now come to the conclusion that the only way to achieve a Code Editor in App SDK / Project Reunion (without html-based wrappers like MonacoEditor) is using the existing text editing logic of e.g. AvalonEdit and to replace the old Windows.Forms-based text rendering logic with Win2D (CanvasDrawingSession.DrawText). Which is a huge pain 😅

**Comment by Overrided** [comment]
Hi guys
Any update on this issue so far?
At the time of writing this comment, Windows App SDK version `1.1` is available and features `Text Rendering` (for full `WinUI3` apps).
Maybe you can add `TextRendering` `c#/xaml` example for full `WinUI3` apps-only for time being (until XAML Islands are released)?

**Comment by duncanmacmichael** [comment]
Hi @Overrided, no, no updates on this issue, sorry. DWriteCore remains a nano-COM C++ API and does not have a C# version available. WinUI3 supports several different project templates, including C#-based and C++-based desktop apps. To use DWriteCore you'll need to write a C++-based app - details as to why are explained above. Stay tuned for future DWriteCore directional updates though - if anything changes with its availability we'll let you know! :)
